### ISSUE TITLE
Should the Changelog start with 1.0.0 ?

### ISSUE THREAD

**Issue by sthiele** [krr-up/python-project-template#34]
Usually when one starts a project it takes some time until a 1.0 release. Having the 1.0.0 as a default in the changelog might / give a wrong impression about the maturity of the project.

**Comment by rkaminsk** [comment]
> Usually when one starts a project it takes some time until a 1.0 release. Having the 1.0.0 as a default in the changelog might / give a wrong impression about the maturity of the project.

In my latest PR, I am using setuptools-scm to infer the version. If there is no version, it starts with 0.1. We can use this as a version. In any case, this was more about having a changes file in place. It has to be modified before the first release anyway.
